### ISSUE TITLE
avoid sending exceedingly large embeds during `!calc`

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#363]
See conversation on https://github.com/duck-dynasty/duckbot/pull/358 (thread starting with "RE: `query`").

As part of this, it'd also be nice to change the default query to be _charizard curve_.

**Comment by twentylemon** [comment]
There's also limitations on the length of embed field names; when searching for "dogs" :
```
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 994, in invoke
    await ctx.command.invoke(ctx)
  File "/opt/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 894, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/opt/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 176, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In embeds.3.fields.0.name: Must be 256 or fewer in length.
```
