### ISSUE TITLE
stock info is crashing due to unsupported locale setting

### ISSUE THREAD

**Issue by twentylemon** [duck-dynasty/duckbot#447]
Prod log:

```
message = $amzn me bro
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/discord/client.py", line 351, in _run_event
    await coro(*args, **kwargs)
  File "/duckbot/duckbot/cogs/fortune/stocks.py", line 18, in stock_info
    summaries = [self.get_stock_summary(ticker) for ticker in map(self.get_ticker, symbols) if ticker]
  File "/duckbot/duckbot/cogs/fortune/stocks.py", line 18, in <listcomp>
    summaries = [self.get_stock_summary(ticker) for ticker in map(self.get_ticker, symbols) if ticker]
  File "/duckbot/duckbot/cogs/fortune/stocks.py", line 31, in get_stock_summary
    locale.setlocale(locale.LC_MONETARY, "en_US.UTF-8")
  File "/usr/local/lib/python3.8/locale.py", line 608, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

**Comment by twentylemon** [comment]
From [stackoverflow](https://stackoverflow.com/questions/14547631/python-locale-error-unsupported-locale-setting), seems it could be the docker image doesn't have the locale available, somehow (even though it's en_us?). Should at least be re-producable when running the full container.
